// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHoheQYJwAOLTT8X5Me9QV1Uy9RSFrME4',
    appId: '1:839684579844:web:4972e915301c46ad3ecb51',
    messagingSenderId: '839684579844',
    projectId: 'attedance-c13a5',
    authDomain: 'attedance-c13a5.firebaseapp.com',
    storageBucket: 'attedance-c13a5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq3UZKb0yEEsrAhqa4TpXyy4CcvufHkjE',
    appId: '1:839684579844:android:d3689d0beb7257693ecb51',
    messagingSenderId: '839684579844',
    projectId: 'attedance-c13a5',
    storageBucket: 'attedance-c13a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh_3k0SbCMHZxxEA79kY0JQKp7ubOptq0',
    appId: '1:839684579844:ios:78b99135fd87bda23ecb51',
    messagingSenderId: '839684579844',
    projectId: 'attedance-c13a5',
    storageBucket: 'attedance-c13a5.appspot.com',
    iosBundleId: 'com.example.attedance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCh_3k0SbCMHZxxEA79kY0JQKp7ubOptq0',
    appId: '1:839684579844:ios:49f577bd44466cd13ecb51',
    messagingSenderId: '839684579844',
    projectId: 'attedance-c13a5',
    storageBucket: 'attedance-c13a5.appspot.com',
    iosBundleId: 'com.example.attedance.RunnerTests',
  );
}
